#!/bin/bash

POLICY=""
EFFECT=""
QUERY=""
POSITIONAL=()
while [[ $# -gt 0 ]]
do
key="$1"

case $key in
    -q|--q|--query)
    QUERY="$2"
    shift # past argument
    shift # past value
    ;; 
    -e|--e|--effect)
    EFFECT="$2"
    shift # past argument
    shift # past value
    ;;
	-c|--c|--create)
    POLICY="$2"
    shift # past argument
    shift # past value
    ;;
    *)    # unknown option
    POSITIONAL+=("$1") # save it in an array for later
    shift # past argument
    ;;
esac
done
set -- "${POSITIONAL[@]}" # restore positional parameters

if [ -z "$POLICY" ]
then
eval ./armclient post '"/providers/Microsoft.ResourceGraph/resources/policy?api-version=2018-09-01-preview&effect='${EFFECT:-audit}'"' '"'${QUERY}'"'| sed '1 d'
else
p=$(eval ./armclient post '"/providers/Microsoft.ResourceGraph/resources/policy?api-version=2018-09-01-preview&effect='${EFFECT:-audit}'"' '"'${QUERY}'"'| sed '1 d')
az policy definition create --rules "${p: 18:-1}" -n "$POLICY" --display-name "$POLICY"
fi

